name: q_in_app_purchase
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  in_app_purchase: any
  q_common_utils:
    path: ../q_common_utils
  q_theme: 
    path: ../q_theme
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
